name: reusable-ci

on:
  workflow_call:
    inputs:
      language:
        required: false
        type: string
        default: node
      node-version:
        required: false
        type: string
        default: '20'
      python-version:
        required: false
        type: string
        default: '3.12'
      install:
        required: false
        type: string
        default: ''
      lint:
        required: false
        type: string
        default: ''
      test:
        required: false
        type: string
        default: ''
    secrets:
      NPM_TOKEN:
        required: false

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (if language=node)
        if: inputs.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          registry-url: https://registry.npmjs.org

      - name: Setup Python (if language=python)
        if: inputs.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Install
        if: inputs.install != ''
        run: ${{ inputs.install }}

      - name: Lint
        if: inputs.lint != ''
        run: ${{ inputs.lint }}

      - name: Test
        if: inputs.test != ''
        run: ${{ inputs.test }}
